providers = ["node"]

[variables]
NIXPACKS_SPA_CADDY = "false"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm ci --omit=dev=false",
  "cd client && npm ci"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "npx tsc --skipLibCheck --project tsconfig.deploy.json"
]

[start]
cmd = "NODE_ENV=production node dist/server/index.js"
