#!/bin/bash

# This script prepares the application for deployment by
# applying fixes for TypeScript type mismatches between
# string and number values in database operations

echo "Preparing application for deployment..."

# Make sure TS_NODE_TRANSPILE_ONLY is set
if ! grep -q "TS_NODE_TRANSPILE_ONLY=true" .env 2>/dev/null; then
  echo 'TS_NODE_TRANSPILE_ONLY=true' >> .env
  echo "Added TS_NODE_TRANSPILE_ONLY=true to .env file"
fi

# Run the fix-deployment-issues.js script
node scripts/fix-deployment-issues.js

# Make bash script executable
chmod +x scripts/prepare-deploy.sh

# Create deployment typings file
cat > deployment.d.ts << EOL
// This file is automatically generated during deployment preparation
// It adds type definitions that help with string/number type conversions in the database

declare namespace NodeJS {
  interface ProcessEnv {
    TS_NODE_TRANSPILE_ONLY: string;
  }
}

// Allow string/number conversions where needed
interface Number {
  toString(): string;
}

interface String {
  toNumber(): number;
}

// Add toString method to String prototype if it doesn't exist
if (!String.prototype.toNumber) {
  String.prototype.toNumber = function(): number {
    return Number(this);
  };
}
EOL

echo "Deployment preparation complete."
echo "You can now deploy your application!"